# Generated by Django 5.0.14 on 2025-04-13 13:21

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='أدخل اسم القسم، يجب أن يكون فريدًا.', max_length=100, unique=True, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True, help_text='أدخل وصفًا اختياريًا للقسم.', null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='أدخل المسمى الوظيفي، يجب أن يكون فريدًا.', max_length=100, unique=True, verbose_name='المسمى الوظيفي')),
                ('description', models.TextField(blank=True, help_text='أدخل وصفًا اختياريًا للمسمى الوظيفي.', null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='الكود الفريد للموظف داخل الشركة.', max_length=20, unique=True, verbose_name='الكود الوظيفي')),
                ('full_name', models.CharField(help_text='اسم الموظف بالكامل.', max_length=255, verbose_name='الاسم الكامل')),
                ('national_id', models.CharField(help_text='الرقم القومي المكون من 14 رقمًا.', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقمًا.', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('phone_number', models.CharField(blank=True, help_text='رقم الهاتف المحمول أو الأرضي.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='رقم الهاتف يجب أن يكون بتنسيق صحيح (مثال: +201xxxxxxxxx أو 01xxxxxxxxx).', regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, help_text='عنوان سكن الموظف.', null=True, verbose_name='العنوان')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], help_text='جنس الموظف.', max_length=1, verbose_name='النوع')),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'أعزب/عزباء'), ('M', 'متزوج/متزوجة'), ('D', 'مطلق/مطلقة'), ('W', 'أرمل/أرملة')], help_text='الحالة الاجتماعية للموظف.', max_length=1, null=True, verbose_name='الحالة الاجتماعية')),
                ('date_of_birth', models.DateField(blank=True, help_text='تاريخ ميلاد الموظف.', null=True, verbose_name='تاريخ الميلاد')),
                ('hiring_date', models.DateField(default=datetime.date.today, help_text='تاريخ بدء العمل الرسمي للموظف.', verbose_name='تاريخ التعيين')),
                ('standard_working_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='عدد ساعات العمل اليومية المطلوبة من الموظف.', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد ساعات العمل القياسية')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='المرتب الشهري الأساسي قبل أي إضافات أو خصومات.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المرتب الأساسي')),
                ('transportation_allowance', models.DecimalField(decimal_places=2, default=0.0, help_text='بدل المواصلات الشهري إن وجد.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بدل المواصلات')),
                ('phone_package', models.DecimalField(decimal_places=2, default=0.0, help_text='قيمة باقة الهاتف الشهرية المخصصة للموظف إن وجدت.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='باقة الهاتف')),
                ('social_insurance_number', models.CharField(blank=True, help_text='الرقم التأميني الخاص بالموظف.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم التأميني يجب أن يحتوي على أرقام فقط.', regex='^\\d+$')], verbose_name='الرقم التأميني')),
                ('insurance_status', models.CharField(choices=[('N', 'غير مؤمن عليه'), ('A', 'نشط'), ('S', 'موقوف')], default='N', help_text='حالة اشتراك الموظف في التأمينات الاجتماعية.', max_length=1, verbose_name='الحالة التأمينية')),
                ('insured_salary', models.DecimalField(blank=True, decimal_places=2, help_text='الأجر الذي يتم حساب التأمينات على أساسه.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الأجر التأميني')),
                ('insurance_subscription_start_date', models.DateField(blank=True, help_text='تاريخ بدء سريان التأمين على الموظف.', null=True, verbose_name='تاريخ بدء الاشتراك في التأمينات')),
                ('annual_leave_entitlement', models.PositiveIntegerField(default=21, help_text='عدد أيام الإجازة الاعتيادية المستحقة للموظف سنويًا.', verbose_name='رصيد الإجازة الاعتيادية السنوي')),
                ('casual_leave_entitlement', models.PositiveIntegerField(default=7, help_text='عدد أيام الإجازة العارضة المستحقة للموظف سنويًا.', verbose_name='رصيد الإجازة العارضة السنوي')),
                ('sick_leave_entitlement', models.PositiveIntegerField(default=14, help_text='عدد أيام الإجازة المرضية المستحقة للموظف سنويًا (قد يكون غير محدود أو حسب القانون).', verbose_name='رصيد الإجازة المرضية السنوي')),
                ('performance_evaluation', models.TextField(blank=True, help_text='آخر تقييم لأداء الموظف وملاحظاته.', null=True, verbose_name='التقييم السنوي/الدوري للأداء')),
                ('salary_increase_rate', models.DecimalField(blank=True, decimal_places=2, help_text='نسبة الزيادة المتوقعة في الراتب بناءً على التقييم أو السياسات.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='معدل الزيادة السنوية/الدورية المتوقعة (%)')),
                ('is_active', models.BooleanField(default=True, help_text='هل الموظف يعمل حاليًا في الشركة؟ (لأغراض الأرشفة)', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('department', models.ForeignKey(help_text='القسم الذي ينتمي إليه الموظف.', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department', verbose_name='القسم')),
                ('job_title', models.ForeignKey(help_text='المسمى الوظيفي للموظف.', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobtitle', verbose_name='المسمى الوظيفي')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['full_name'],
            },
        ),
    ]
