# Generated by Django 5.0.14 on 2025-07-08 13:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفون'},
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(default=1, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_entitlement',
            field=models.PositiveIntegerField(default=21, verbose_name='رصيد الإجازة السنوية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الأساسي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='casual_leave_entitlement',
            field=models.PositiveIntegerField(default=7, verbose_name='رصيد الإجازة العرضية'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود الموظف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='الاسم بالكامل'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(verbose_name='تاريخ التعيين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_status',
            field=models.CharField(blank=True, choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق')], max_length=10, verbose_name='حالة التأمين'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insurance_subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الاشتراك'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='insured_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب المؤمن عليه'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.jobtitle', verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('S', 'أعزب'), ('M', 'متزوج'), ('D', 'مطلق'), ('W', 'أرمل')], max_length=1, verbose_name='الحالة الاجتماعية'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='performance_evaluation',
            field=models.CharField(blank=True, default=1, max_length=2, verbose_name='تقييم الأداء'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_package',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بدل هاتف'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_increase_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نسبة زيادة الراتب'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sick_leave_entitlement',
            field=models.PositiveIntegerField(default=14, verbose_name='رصيد الإجازة المرضية'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='employee',
            name='standard_working_hours',
            field=models.PositiveIntegerField(default=8, verbose_name='ساعات العمل المعتادة'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بدل مواصلات'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='المسمى الوظيفي'),
        ),
    ]
