# Generated by Django 5.0.14 on 2025-07-08 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_options_alter_department_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='اسم الجهاز')),
                ('ip_address', models.CharField(max_length=15, verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='المنفذ')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم التسلسلي')),
                ('model', models.CharField(max_length=50, verbose_name='الموديل')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('maintenance', 'صيانة')], default='active', max_length=11, verbose_name='الحالة')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('sync_interval', models.PositiveIntegerField(default=15, verbose_name='فترة المزامنة (دقائق)')),
                ('location', models.CharField(max_length=100, verbose_name='الموقع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'جهاز ZK',
                'verbose_name_plural': 'أجهزة ZK',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_insurance_number',
            field=models.CharField(blank=True, default=1, max_length=20, verbose_name='رقم التأمين الاجتماعي'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ZKSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت المزامنة')),
                ('records_fetched', models.PositiveIntegerField(verbose_name='عدد السجلات المستلمة')),
                ('status', models.CharField(max_length=20, verbose_name='حالة المزامنة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدة المزامنة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.zkdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل مزامنة ZK',
                'verbose_name_plural': 'سجلات مزامنة ZK',
                'ordering': ['-sync_time'],
            },
        ),
        migrations.CreateModel(
            name='ZKAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='وقت التسجيل')),
                ('status', models.CharField(choices=[('check_in', 'حضور'), ('check_out', 'انصراف')], max_length=10, verbose_name='الحالة')),
                ('device_user_id', models.CharField(max_length=20, verbose_name='معرف المستخدم بالجهاز')),
                ('is_processed', models.BooleanField(default=False, verbose_name='تمت معالجته')),
                ('raw_data', models.TextField(blank=True, verbose_name='البيانات الخام')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.zkdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل حضور ZK',
                'verbose_name_plural': 'سجلات حضور ZK',
                'indexes': [models.Index(fields=['employee', 'record_time'], name='employees_z_employe_1f0f8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeviceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=20, unique=True, verbose_name='معرف المستخدم بالجهاز')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.zkdevice', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'تعيين موظف لجهاز',
                'verbose_name_plural': 'تعيينات الموظفين للأجهزة',
                'unique_together': {('employee', 'device')},
            },
        ),
    ]
